### ISSUE TITLE
Add a description to the project

### ISSUE THREAD

**Issue by Jonasvdbo** [alliander-opensource/power-grid-model-workshop#2]
**Is your feature request related to a problem? Please describe.**
The current about description of the project does not make clear what the scope and purpose of the project is.

![image](https://user-images.githubusercontent.com/3628277/178456514-601ca89b-493f-477f-bf3e-6b431bfd3074.png)

**Describe the solution you'd like**
My suggestion would be to add a description.

**Comment by Jonasvdbo** [comment]
@nitbharambe  I am just following up to check what you think of my suggestion

**Comment by nitbharambe** [comment]
Added a description. Thanks for pointing that out!
