### ISSUE TITLE
Line 7 -> Line 2007

### ISSUE THREAD

**Issue by FrankKr** [alliander-opensource/power-grid-model-workshop#9]
![image](https://user-images.githubusercontent.com/18208480/220647619-4627a2cb-7063-414c-8e0d-d369416781a8.png)

**Comment by nitbharambe** [comment]
Thanks for raising the issue @FrankKr !
Corrected this in https://github.com/alliander-opensource/power-grid-model-workshop/commit/f61039cd43b3a32801afebdd6637ca28f00665dc
